// <auto-generated />
namespace Mutual.Portal.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _312300p : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_312300p));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120933466_3-12-3-00-p"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
