// <auto-generated />
namespace Mutual.Portal.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _4101119a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4101119a));
        
        string IMigrationMetadata.Id
        {
            get { return "201704100549360_4-10-11-19-a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
