// <auto-generated />
namespace Mutual.Portal.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _311849p : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_311849p));
        
        string IMigrationMetadata.Id
        {
            get { return "201703111523363_3-11-8-49-p"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
