// <auto-generated />
namespace Mutual.Portal.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _312926a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_312926a));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120356563_3-12-9-26-a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
